# Generated by Django 5.2 on 2025-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
